//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_id { get; set; }
        public string EmpName { get; set; }
        public string EmpDept { get; set; }
        public string EmpContactNo { get; set; }
        public string EmpProject { get; set; }
    }
}
